<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AssemblyName>bootstrap</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AWSProjectType>Lambda</AWSProjectType>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <PublishAot>true</PublishAot>
        <StripSymbols>true</StripSymbols>
        <TrimMode>partial</TrimMode>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="3.0.1" />
        <PackageReference Include="Amazon.Lambda.Logging.AspNetCore" Version="5.0.0" />
        <PackageReference Include="Amazon.Lambda.RuntimeSupport" Version="2.2.0" />
        <PackageReference Include="Amazon.Lambda.Core" Version="3.3.0" />
        <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="3.0.1" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\MediaIngestionApi.Infrastructure\MediaIngestionApi.Infrastructure.csproj" />
    </ItemGroup>
    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>
</Project>